config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  root to: 'plans#index'
  resources :plans
  resources :shoes, only: %i[new create index show destroy edit update]
  resources :shoe_brands, only: %i[index create edit update]
  resources :shoe_sizes, only: %i[index create edit update]
  resources :users, only: %i[index edit show update] do
    resource :relationships, only: %i[create destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  resources :shoes do
    resources :favorites, only: %i[create destroy]
    resources :comments, only: %i[create destroy]
  end

  resources :shoes do
    collection do
      get :search
    end
  end
  post '/homes/guest_sign_in', to: 'homes#new_guest'
end

app/models/after_image.rb
class AfterImage < ApplicationRecord
  belongs_to :shoe
  attachment :after_image
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :shoe
  validates :comment, presence: true, length: { minimum: 1 }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :shoe
end

app/models/plan.rb
class Plan < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: { minimum: 2 }
  validates :content, presence: true, length: { maximum: 200 }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
end

app/models/shoe.rb
class Shoe < ApplicationRecord
  belongs_to :user
  has_many :shoe_images, dependent: :destroy
  has_many :after_images, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :tags, dependent: :destroy
  accepts_attachments_for :shoe_images, attachment: :before_image
  accepts_attachments_for :after_images, attachment: :after_image
  belongs_to :shoe_brand, optional: true
  belongs_to :shoe_size, optional: true
  validates :shoe_model, length: { maximum: 50, minimum: 2 }, presence: true
  validates :description, length: { maximum: 200 }
  validates :shoe_images, presence: true
  validates :after_images, presence: true
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/shoe_brand.rb
class ShoeBrand < ApplicationRecord
  has_many :shoe
  with_options presence: true do
    validates :brand_name
  end
end

app/models/shoe_image.rb
class ShoeImage < ApplicationRecord
  belongs_to :shoe
  attachment :before_image
end

app/models/shoe_size.rb
class ShoeSize < ApplicationRecord
  has_many :shoe
  with_options presence: true do
    validates :size
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :shoe
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image, destroy: false

  has_many :shoes
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :plans
  validates :name, length: { maximum: 20, minimum: 2 }, uniqueness: true, presence: true
  validates :introduction,
            length: { maximum: 50 }
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy
  has_many :relationships, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :followings, through: :relationships, source: :followed

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @shoes = @user.shoes.all.page(params[:page]).per(5)
    @shoe = Shoe.new
    @plans = Plan.where(user_id: @user.id).where(start_time: Time.current.to_date.beginning_of_day .. Time.current.to_date.end_of_day)
  end

  def index
    @user = User.all.page(params[:page]).per(5)
    @shoes = Shoe.all
    @users = current_user
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = 'successfully'
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/shoe_sizes_helper.rb
module ShoeSizesHelper
end

app/helpers/shoes_brands_helper.rb
module ShoesBrandsHelper
end

app/helpers/shoes_helper.rb
module ShoesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <% if @user.errors.any? %>
      <%= @user.errors.count %>error prohibited this obj from being saved:
      <% @user.errors.full_messages.each do |message| %>
      <%= message %>
      <% end %>
    <% end %>
    <%= form_with model:@user, local:true do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
      <div class="form-group">
        <%= f.label :image %>
        <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
 <div class="row">
   <div class="col-md-3 offset-md-1">
    <h1 class="p-3 md-2 text-dark">User info</h1>
     <%= form_with model:@users, local:true do |f| %>
      <%= attachment_image_tag @users, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"  %>
     <% end %>
     <table class='table'>
      <tr>
       <th>name</th>
    	  <th><%= @users.name %></th>
      </tr>
      <tr>
    	  <th>introduction</th>
    	  <th><%= @users.introduction %></th>
      </tr>
      <tr>
      <% user ||= current_user %>
      <div class="stats">
    	  <th>follows</th>
    	  <th>
          <strong id="following" class="stat">
          <%= user.followings.count %>
          </strong>
        </th>
      </tr>
      <tr>
    	  <th>followers</th>
    	  <th>
    	    <strong id="followers" class="stat">
          <%= user.followers.count %>
          </strong>
        </th>
      </tr>
    </div>
  </table>

  <% if @users.id == current_user.id %>
      <%= link_to '',edit_user_path(user),class: "btn btn-outline-secondary btn-block fas fa-user-cog text-primary edit_user_#{user.id}" %>
      <%= link_to '予定の追加・確認', plans_path(current_user.id),class: 'btn btn-outline-secondary btn-block fas fa-calendar-week nav-link text-primary' %>
  <% end %>
  </div>



<div class="col-md-6 offset-md-1">
  <h1 class="p-3 md-2 text-dark">Users</h1>

<table class="table">
 <table>
  <thead>
   <tr>
    <th>Image</th>
    <th>UserName</th>
   </tr>
 </thead>

 <% @user.each do |user| %>
 <tbody>
   <tr>
    <th><%= attachment_image_tag user, :profile_image,  :fill, 60, 60, fallback: "no_image.jpg" %></th>
    <td>
     <%= link_to user_path(user.id) do %>
     <%= user.name %>
     <% end %>
    </td>
    <td>フォロー数: <%= user.followings.count %></td>
    <td>フォロワー数: <%= user.followers.count %></td>
    <td>
      <% if current_user != user %>
       <% if current_user.following?(user) %>
        <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class: 'btn btn-info' %>
       <% else %>
        <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: 'btn btn-info' %>
       <% end %>
      <% end %>
    </td>
   </tr>
 </tbody>
 <% end %>
</table>
 <div class="pagination">
   <%= paginate(@user) %>
 </div>
 </div>
 </div>

app/views/users/show.html.erb
<% if @user.id == current_user.id %>

<% if @plans.exists? %>
<div class="row">
    <div class="col-md-6 offset-md-3 text-center">
        <h4 class="p-3 md-2 text-dark">Today's_Plan</h4>
         <table class='table'>
            <thead>
                <tr>
                    <th>Strat_Time</th>
                    <th>Title</th>
                </tr>
            </thead>
            <% @plans.each do |plan| %>
                <tr>
                    <th><%= plan.start_time.strftime('%H:%M') %></th>
                    <th><%= plan.title %></th>
                </tr>
            <% end %>
         </table>
    </div>
</div>
<% end %>
<% end %>

<div class="row">
    <div class="col-md-3 offset-md-1">
        <% if @user.id == current_user.id %>
        <h1 class="p-3 md-2 text-dark">MyPage</h1>
        <% else %>
        <h1 class="p-3 md-2 text-dark">User info</h1>
        <% end %>
        <%= form_with model:@user, local:true do |f| %>
        <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"  %>
        <% end %>
        <table class='table'>
            <tr>
                <th>name</th>
                <th><%= @user.name %></th>
            </tr>
            <tr>
                <th>introduction</th>
                <th><%= @user.introduction %></th>
            </tr>
            <tr>
                <% user ||= current_user %>
                <div class="stats">
                    <th>follows</th>
                    <th>
                        <strong id="following" class="stat">
                            <%= user.followings.count %>
                        </strong>
                    </th>
                </div>
            </tr>
            <tr>
                <th>followers</th>
                <th>
                    <strong id="followers" class="stat">
                        <%= user.followers.count %>
                    </strong>
                </th>
            </tr>
        </table>
        <% if @user.id == current_user.id %>
        <%= link_to '',edit_user_path(user),class: "btn btn-outline-secondary btn-block fas fa-user-cog text-primary edit_user_#{user.id}" %>
        <%= link_to '予定の追加・確認', plans_path(current_user.id),class: 'btn btn-outline-secondary btn-block fas fa-calendar-week nav-link text-primary' %>
        <% end %>
    </div>



    <div class="col-md-6 offset-md-1">
        <h1 class="p-3 md-2 text-dark"><%= @user.name %>'s_Shoes rack</h1>
        <table class='table'>
            <thead>
                <tr>
                    <th></th>
                    <th>シューズブランド</th>
                    <th>シューズモデル・デザイン </th>
                    <th>シューズサイズ</th>
                </tr>
            </thead>

            <% @shoes.each do |shoe| %>

                <tr>
                    <th></th>
                    <th><%= shoe.shoe_brand.brand_name %></th>
                    <th>
                        <%= link_to shoe_path(shoe.id) do %>
                        <%= shoe.shoe_model %>
                        <% end %>
                    </th>
                    <th><%= shoe.shoe_size.size %></th>
                </tr>
            <% end %>
        </table>
    <div class="paginate">
        <%= paginate(@shoes) %>
    </div>
    </div>
 </div>