config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  root to: 'plans#index'
  resources :plans
  resources :shoes, only: %i[new create index show destroy edit update]
  resources :shoe_brands, only: %i[index create edit update]
  resources :shoe_sizes, only: %i[index create edit update]
  resources :users, only: %i[index edit show update] do
    resource :relationships, only: %i[create destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  resources :shoes do
    resources :favorites, only: %i[create destroy]
    resources :comments, only: %i[create destroy]
  end

  resources :shoes do
    collection do
      get :search
    end
  end
  post '/homes/guest_sign_in', to: 'homes#new_guest'
end

app/models/after_image.rb
class AfterImage < ApplicationRecord
  belongs_to :shoe
  attachment :after_image
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :shoe
  validates :comment, presence: true, length: { minimum: 1 }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :shoe
end

app/models/plan.rb
class Plan < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: { minimum: 2 }
  validates :content, presence: true, length: { maximum: 200 }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
end

app/models/shoe.rb
class Shoe < ApplicationRecord
  belongs_to :user
  has_many :shoe_images, dependent: :destroy
  has_many :after_images, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :tags, dependent: :destroy
  accepts_attachments_for :shoe_images, attachment: :before_image
  accepts_attachments_for :after_images, attachment: :after_image
  belongs_to :shoe_brand, optional: true
  belongs_to :shoe_size, optional: true
  validates :shoe_model, length: { maximum: 50, minimum: 2 }, presence: true
  validates :description, length: { maximum: 200 }
  validates :shoe_images, presence: true
  validates :after_images, presence: true
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/shoe_brand.rb
class ShoeBrand < ApplicationRecord
  has_many :shoe
  with_options presence: true do
    validates :brand_name
  end
end

app/models/shoe_image.rb
class ShoeImage < ApplicationRecord
  belongs_to :shoe
  attachment :before_image
end

app/models/shoe_size.rb
class ShoeSize < ApplicationRecord
  has_many :shoe
  with_options presence: true do
    validates :size
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :shoe
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image, destroy: false

  has_many :shoes
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :plans
  validates :name, length: { maximum: 20, minimum: 2 }, uniqueness: true, presence: true
  validates :introduction,
            length: { maximum: 50 }
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy
  has_many :relationships, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :followings, through: :relationships, source: :followed

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  def index
    @plans = Plan.where(user_id: current_user).page(params[:page]).per(5)
  end

  def new
    @plan = Plan.new
  end

  def show
    @plan = Plan.find(params[:id])
  end

  def create
    @plan = Plan.new(plan_parameter)
    @plan.user_id = current_user.id
    if @plan.save
      redirect_to plan_path(@plan)
    else
      render :new
    end
  end

  def destroy
    @plan = Plan.find(params[:id])
    @plan.destroy
    redirect_to plans_path, notice: '削除しました'
  end

  def edit
    @plan = Plan.find(params[:id])
  end

  def update
    @plan = Plan.find(params[:id])
    if @plan.update(plan_parameter)
      redirect_to plans_path, notice: '編集しました'
    else
      render 'edit'
    end
  end

  private

  def plan_parameter
    params.require(:plan).permit(:title, :content, :start_time)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/shoe_sizes_helper.rb
module ShoeSizesHelper
end

app/helpers/shoes_brands_helper.rb
module ShoesBrandsHelper
end

app/helpers/shoes_helper.rb
module ShoesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/plans/edit.html.erb
<div class="row">
 <div class="col-md-7 offset-md-2">
   <h3 class="p-3 md-2 text-dark">Edit</h3>
    <%= form_with(model: @plan, local: true) do |form| %>

      <div class="title">
        <%= form.label :title %>
        <%= form.text_field :title %>
      </div>

      <div class="time">
        <%= form.label :start_time %>
        <%= form.datetime_select :start_time %>
      </div>

      <div class="content">
        <%= form.label :content %>
        <%= form.text_field :content %>
      </div>


      <div class="submit">
        <%= form.submit %>
      </div>

    <% end %>
  </div>
</div>

app/views/plans/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
 <div class="col-md-7 offset-md-2">
  <h1 class="p-3 md-2 text-dark">Shoe_polish Plans </h1>

  <table>
    <thead>
      <tr>
        <th>タイトル</th>
        <th>時間</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @plans.each do |plan| %>
      <tr>
        <td><%= plan.title %></td>
        <td><%= plan.start_time.strftime("%Y-%m-%d %H:%M") %></td>
        <td><%= link_to 'Show', plan, class: 'btn btn-sm btn-info' %></td>
        <td><%= link_to 'Edit', edit_plan_path(plan.id), class: "btn btn-sm btn-success" %></td>
        <td><%= link_to 'Destroy',plan_path(plan.id), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-danger" %></td>
      </tr>
      <% end %>
    </tbody>
  </table>


  <div class="pagination">
    <%= paginate(@plans) %>
  </div>


  <br>
    <%= link_to '予定を追加', new_plan_path, class: "btn btn-primary" %>
    <%= month_calendar events: @plans do |date, plans| %>
    <%= date.day %>
    <% plans.each do |plan| %>
  <div>
    <%= link_to plan.title, plan %>
  </div>
  <% end %>
  <% end %>
 </div>
</div>

app/views/plans/new.html.erb
<% if @plan.errors.any? %>
    <%= @plan.errors.count %>error prohibited this obj from being saved:
    <% @plan.errors.full_messages.each do |message| %>
    <%= message %>
    <% end %>
<% end %>
<div class="row">
 <div class="col-md-7 offset-md-2">
  <h3 class="p-3 md-2 text-dark">Plans Create</h3>


  <%= form_with(model: @plan, local: true) do |form| %>

  <div class="title">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

    <div class="time">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time %>
  </div>

  <div class="content">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>


  <div class="submit">
    <%= form.submit %>
  </div>

  <% end %>
 </div>
</div>

app/views/plans/show.html.erb
<div class="row">
 <div class="col-md-7 offset-md-2">
   <h3 class="p-3 md-2 text-dark">Show</h3>
    <p id="notice"><%= notice %></p>

    <p>
      <strong>タイトル</strong>
      <%= @plan.title %>
    </p>

    <p>
      <strong>時間</strong>
      <%= @plan.start_time.strftime("%Y-%m-%d %H:%M") %>
    </p>

    <p>
      <strong>内容</strong>
      <%= @plan.content %>
    </p>

    <%= link_to 'Edit', edit_plan_path(@plan) %> |
    <%= link_to 'Back', plans_path %>
    </div>
  </div>
</div>