config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  root to: 'plans#index'
  resources :plans
  resources :shoes, only: %i[new create index show destroy edit update]
  resources :shoe_brands, only: %i[index create edit update]
  resources :shoe_sizes, only: %i[index create edit update]
  resources :users, only: %i[index edit show update] do
    resource :relationships, only: %i[create destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  resources :shoes do
    resources :favorites, only: %i[create destroy]
    resources :comments, only: %i[create destroy]
  end

  resources :shoes do
    collection do
      get :search
    end
  end
  post '/homes/guest_sign_in', to: 'homes#new_guest'
end

app/models/after_image.rb
class AfterImage < ApplicationRecord
  belongs_to :shoe
  attachment :after_image
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :shoe
  validates :comment, presence: true, length: { minimum: 1 }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :shoe
end

app/models/plan.rb
class Plan < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: { minimum: 2 }
  validates :content, presence: true, length: { maximum: 200 }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
end

app/models/shoe.rb
class Shoe < ApplicationRecord
  belongs_to :user
  has_many :shoe_images, dependent: :destroy
  has_many :after_images, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :tags, dependent: :destroy
  accepts_attachments_for :shoe_images, attachment: :before_image
  accepts_attachments_for :after_images, attachment: :after_image
  belongs_to :shoe_brand, optional: true
  belongs_to :shoe_size, optional: true
  validates :shoe_model, length: { maximum: 50, minimum: 2 }, presence: true
  validates :description, length: { maximum: 200 }
  validates :shoe_images, presence: true
  validates :after_images, presence: true
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/shoe_brand.rb
class ShoeBrand < ApplicationRecord
  has_many :shoe
  with_options presence: true do
    validates :brand_name
  end
end

app/models/shoe_image.rb
class ShoeImage < ApplicationRecord
  belongs_to :shoe
  attachment :before_image
end

app/models/shoe_size.rb
class ShoeSize < ApplicationRecord
  has_many :shoe
  with_options presence: true do
    validates :size
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :shoe
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image, destroy: false

  has_many :shoes
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :plans
  validates :name, length: { maximum: 20, minimum: 2 }, uniqueness: true, presence: true
  validates :introduction,
            length: { maximum: 50 }
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy
  has_many :relationships, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :followings, through: :relationships, source: :followed

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end
end

app/controllers/shoes_controller.rb
class ShoesController < ApplicationController
  def new
    @shoe = Shoe.new
    @shoe.shoe_images.build
    @shoe_brand = ShoeBrand.all.order("brand_name ASC")
    @shoe_size = ShoeSize.all
  end

  def create
    @shoe = Shoe.new(shoe_params)
    @shoe.score = Language.get_data(shoe_params[:description])
    @shoe.user_id = current_user.id
    if @shoe.save
      tags = []
      @shoe.after_images.each do |after_image|
        tags.concat(Vision.get_image_data(after_image.after_image))
      end
      @shoe.shoe_images.each do |shoe_image|
        tags.concat(Vision.get_image_data(shoe_image.before_image))
      end
      tags.each do |tag|
        @shoe.tags.create(name: tag)
      end
      redirect_to shoe_path(@shoe)
    else
      render :new
    end
  end

  def index
    if params[:q]
      @search = Shoe.ransack(params[:q])
      @shoes = @search.result(distinct: true).order(created_at: 'DESC').includes(:user).page(params[:page]).per(5)
      pp @shoes
    else
      @shoes = Shoe.all.page(params[:page]).per(5)
    end
  end

  def show
    @shoe = Shoe.find(params[:id])
    @comment = Comment.new
    @comments = @shoe.comments.order(created_at: :desc)
    @favorite = @shoe.favorites.find_by(user_id: current_user.id)
  end

  def destroy
    @shoe = Shoe.find(params[:id])
    @shoe.destroy
    redirect_to shoes_path
  end

  def edit
    @shoe = Shoe.find(params[:id])
    @shoe_brand = ShoeBrand.all
    @shoe_size = ShoeSize.all
  end

  def update
    @shoe = Shoe.find(params[:id])
    if @shoe.update(shoe_params)
      redirect_to shoe_path(@shoe), notice: 'You have updated plans successfully.'
    else
      render 'edit'
    end
  end

  private

  def shoe_params
    params.require(:shoe).permit(:shoes_models, :description, :shoe_model, :shoe_brand_id, :shoe_size_id,
                                 shoe_images_before_images: [], after_images_after_images: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/shoe_sizes_helper.rb
module ShoeSizesHelper
end

app/helpers/shoes_brands_helper.rb
module ShoesBrandsHelper
end

app/helpers/shoes_helper.rb
module ShoesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/shoes/edit.html.erb
<% if @shoe.errors.any? %>
<div id="error_explanation">
  <ul>
    <% @shoe.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div class="col-md-8 offset-md-2">
  <h1 class="p-3 md-2 text-dark">Editing Post</h1>
</div>
<div class="row">
  <div class="col-md-8 offset-md-2">
    <div class="form-group">
      <%= form_with model: @shoe, url: shoe_path(@shoe), method: :patch, local:true do |f| %>

      <div class="form-group row">
        <p class="col-md-3 pt-1 mb-0">＜Before_Image＞</p>
        <%= f.attachment_field :shoe_images_before_images, multiple: true %>
      </div>

      <div class="form-group row">
        <p class="col-md-3 pt-1 mb-0">＜After_Image＞</p>
        <%= f.attachment_field :after_images_after_images, multiple: true %>
      </div>

      <div class="form-group row">
        <p class="col-md-3 pt-1 mb-0">Shoes_brand</p>
        <%= f.collection_select :shoe_brand_id, @shoe_brand.all, :id , :brand_name %>
      </div>

      <div class="form-group row">
        <p class="col-md-3 pt-1 mb-0">Shoes_model(design)</p>
        <%= f.text_field :shoe_model %>
      </div>

      <div class="form-group row">
        <p class="col-md-3 pt-1 mb-0">Shoes_size</p>
        <%= f.collection_select :shoe_size_id, @shoe_size, :id, :size %>
      </div>

      <div class="form-group row">
        <p class="col-md-3 pt-1 mb-0">introduction</p>
        <%= f.text_area :description, :size=>"25x5" %>
      </div>

      <%= f.submit '変更を保存', class: "btn btn-success" %>
      <% end %>
    </div>
  </div>
</div>

app/views/shoes/index.html.erb
<div class="row">
 <div class="col-md-7 offset-md-2">
  <h1 class="p-3 md-2 text-dark">PostsList</h1>
</div>
</div>

<div class="row">
 <div class="col-md-9 offset-md-2">
  <table class='table'>
   <thead>
    <tr>
     <th></th>
     <th>name</th>
     <th>Shoes_brand</th>
     <th>Shoes_model(design) </th>
     <th>Shoes_size</th>
     <th>favorites</th>
     <th>comments</th>
    </tr>
   </thead>
 </div>
</div>

<% @shoes.each do |shoe| %>

   <tr>
    <th><%= attachment_image_tag shoe.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"  %></th>
    <th>
      <%= link_to user_path(shoe.user.id) do %>
      <%= shoe.user.name %>
      <% end %>
    </th>
    <th><%= shoe.shoe_brand.brand_name %></th>
    <th>
     <%= link_to shoe_path(shoe.id) do %>
     <%= shoe.shoe_model %>
     <% end %>
    </th>
    <th><%= shoe.shoe_size.size %></th>
    <td>
     　♡<%=  "#{shoe.favorites.count} いいね" %>
    </td>
    <td><p><%=  "#{shoe.comments.count} コメント" %></p></td>
    <% if shoe.user==current_user %>
    <td><%= link_to "Edit", edit_shoe_path(shoe.id), class: "btn btn-sm btn-success" %></td>
    <td><%= link_to 'Destroy', shoe_path(shoe), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_shoe_#{shoe.id}"%></td>
    <% end %>
   </tr>
  <% end %>
  </table>

<div class="paginate">
 <%= paginate(@shoes) %>
</div>

app/views/shoes/new.html.erb
<% if @shoe.errors.any? %>
  <div id="error_explanation">
    <ul>
      <% @shoe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class="col-md-8 offset-md-2">
 <h1 class="p-3 md-2 text-dark">NewPost</h1>
</div>
<div class="row">
  <div class="col-md-8 offset-md-2">
    <div class="form-group">

<%= form_with model: @shoe, url: shoes_path, method: :post, local:true do |f| %>

  <div class="form-group row">
    <p class="col-md-3 pt-1 mb-0">＜Before_Image＞</p>
    <%= f.attachment_field :shoe_images_before_images, multiple: true %>
  </div>

   <div class="form-group row">
    <p class="col-md-3 pt-1 mb-0">＜After_Image＞</p>
    <%= f.attachment_field :after_images_after_images, multiple: true %>
  </div>


  <div class="form-group row">
    <p class="col-md-3 pt-1 mb-0">Shoes_brand</p>
    <%= f.collection_select :shoe_brand_id, ShoeBrand.all.order("brand_name ASC"), :id , :brand_name %>
  </div>

   <div class="form-group row">
   <p class="col-md-3 pt-1 mb-0">Shoes_model(design)</p>
   <%= f.text_field :shoe_model %>
  </div>


  <div class="form-group row">
    <p class="col-md-3 pt-1 mb-0">Shoes_size</p>
    <%= f.collection_select :shoe_size_id, ShoeSize.all, :id, :size %>
  </div>

  <div class="form-group row">
   <p class="col-md-3 pt-1 mb-0">introduction</p>
   <%= f.text_area :description, :size=>"25x5" %>
  </div>


 <%= f.submit '新規登録', class: "btn btn-success" %>

 <% end %>

app/views/shoes/show.html.erb
<div class="col-md-8 offset-md-2">
  <h1 class="p-3 md-2  text-dark">Aging Record</h1>
</div>
<div class="row">
  <div class="col-md-10 offset-md-1">
    <div class="text-center">
      <h2>【BEFORE】</h2>
      <% if @shoe.shoe_images.present? %>
        <% @shoe.shoe_images.each do |image| %>
        <%= attachment_image_tag image, :before_image, :fill, 200, 200, fallback: "", class: "default_image" %>
        <% end %>
      <% else %>
        画像はありません。
      <% end %>
      <div class="tag-box">
      <% @shoe.tags.each do |tag| %>
        <span class="label"><%= tag.name %></span>
      <% end %>
      <div>


      <h2>【AFTER】</h2>
      <% if @shoe.after_images.present? %>
        <% @shoe.after_images.each do |image| %>
         <%= attachment_image_tag image, :after_image, :fill, 200, 200, fallback: "", class: "default_image" %>
        <% end %>
      <% else %>
        画像はありません。
      <% end %>
      <div class="tag-box">
      <% @shoe.tags.each do |tag| %>
        <span class="label"><%= tag.name %></span>
      <% end %>
      <div>
       </div>
 　　</div>
　</div>


 <div class="col-md-5 offset-md-4">
   <div class="text-center">
    <table>
      <tr>
       <th>
          <div class="form-group row">
            <p class="col-md-3 pt-1 mb-0">Shoes_brand</p>
       </th>
       <th>
            <%= @shoe.shoe_brand.brand_name %>
          </div>
       </th>
      </tr>
      <tr>
       <th>
          <div class="form-group row">
            <p class="col-md-3 pt-1 mb-0">Shoes_model(design)</p>
        </th>
        <th>
            <%= @shoe.shoe_model %>
          </div>
        </th>
      </tr>
      <tr>
        <th>
          <div class="form-group row">
            <p class="col-md-3 pt-1 mb-0">Shoes_size</p>
        </th>
        <th>
            <%= @shoe.shoe_size.size %>
          </div>
        </th>
      </tr>
      <tr>
       <th>
          <div class="form-group row">
            <p class="col-md-3 pt-1 mb-0">introduction</p>
        </th>
        <th>
            <%= @shoe.description %>
          </div>
        </th>
      </tr>
      <tr>
        <th>
          <div class="form-group row">
            <p class="col-md-5 pt-0 mb-0">introductionの感情分析スコア</p>
        </th>
        <th>
            [<%= @shoe.score %>]
          </div>
        </th>
      </tr>
      <tr>
      <tr>
        <th>
          <div id="favorites_buttons_<%= @shoe.id %>">
            <%= render 'favorites/favorite', shoe: @shoe, favorite: @favorite %>
          </div>
        </th>
      </tr>
      <tr>
        <td>
          <div id="comments_area">
            <%= render 'comments/comment', shoe: @shoe, comment: @comment %>
          </div>
        </td>
      </tr>
      <tr>
        <% if @shoe.user==current_user %>
          <td>
            <div class="mt-5">
              <%= link_to "投稿を編集する", edit_shoe_path(@shoe.id), class: "btn btn-sm btn-success" %>
            </div>
          </td>
          <td>
            <div class="mt-5">
              <%= link_to '投稿を削除する', shoe_path(@shoe), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_shoe_#{@shoe.id}"%>
            </div>
          </td>
        <% end %>
        </div>
      </tr>
    </table>
   </div>
</div>