config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  root to: 'plans#index'
  resources :plans
  resources :shoes, only: %i[new create index show destroy edit update]
  resources :shoe_brands, only: %i[index create edit update]
  resources :shoe_sizes, only: %i[index create edit update]
  resources :users, only: %i[index edit show update] do
    resource :relationships, only: %i[create destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  resources :shoes do
    resources :favorites, only: %i[create destroy]
    resources :comments, only: %i[create destroy]
  end

  resources :shoes do
    collection do
      get :search
    end
  end
  post '/homes/guest_sign_in', to: 'homes#new_guest'
end

app/models/after_image.rb
class AfterImage < ApplicationRecord
  belongs_to :shoe
  attachment :after_image
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :shoe
  validates :comment, presence: true, length: { minimum: 1 }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :shoe
end

app/models/plan.rb
class Plan < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: { minimum: 2 }
  validates :content, presence: true, length: { maximum: 200 }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
end

app/models/shoe.rb
class Shoe < ApplicationRecord
  belongs_to :user
  has_many :shoe_images, dependent: :destroy
  has_many :after_images, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :tags, dependent: :destroy
  accepts_attachments_for :shoe_images, attachment: :before_image
  accepts_attachments_for :after_images, attachment: :after_image
  belongs_to :shoe_brand, optional: true
  belongs_to :shoe_size, optional: true
  validates :shoe_model, length: { maximum: 50, minimum: 2 }, presence: true
  validates :description, length: { maximum: 200 }
  validates :shoe_images, presence: true
  validates :after_images, presence: true
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/shoe_brand.rb
class ShoeBrand < ApplicationRecord
  has_many :shoe
  with_options presence: true do
    validates :brand_name
  end
end

app/models/shoe_image.rb
class ShoeImage < ApplicationRecord
  belongs_to :shoe
  attachment :before_image
end

app/models/shoe_size.rb
class ShoeSize < ApplicationRecord
  has_many :shoe
  with_options presence: true do
    validates :size
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :shoe
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image, destroy: false

  has_many :shoes
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :plans
  validates :name, length: { maximum: 20, minimum: 2 }, uniqueness: true, presence: true
  validates :introduction,
            length: { maximum: 50 }
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy
  has_many :relationships, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :followings, through: :relationships, source: :followed

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/shoe_sizes_helper.rb
module ShoeSizesHelper
end

app/helpers/shoes_helper.rb
module ShoesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shoesproud</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.3.3/css/swiper.min.css"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.3.3/js/swiper.min.js"></script>
  </head>

    <body>
     <header class="bg-dark text-white">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <%= link_to "ShoesProud", root_path, class: 'navbar-brand text-white' %><i class="fas fa-shoe-prints text-white"></i>
          <ul class="navbar-nav ml-auto">
     <% if user_signed_in? %>
     <li>
        <%= link_to 'calenda', plans_path(current_user.id),class: 'fas fa-calendar-week nav-link text-light' %>
     </li>
     <li>
        <%= link_to 'MyPage', user_path(current_user.id),class: 'fas fa-user-tie nav-link text-light' %>
     </li>
     <li>
        <%= link_to 'PostsList', shoes_path,class: 'fas fa-images nav-link text-light' %>
     </li>
     <li>
        <%= link_to 'NewPost', new_shoe_path,class: 'fas fa-edit nav-link text-light' %>
      </li>
      <li>
        <%= link_to "Users", users_path,class: 'fas fa-users nav-link text-light' %>
      </li>
      <li>
        <%= link_to "logout", destroy_user_session_path, method: :delete,class: 'fas fa-sign-out-alt nav-link text-light' %>
      </li>
      <li>
      <%= render 'searches/search' %>
        <div class= "container-fluid">
         <div class=  "row.py-5.w-100">
          <div class=  "jscroll">
          </div>
         </div>
        </div>
      </li>
     <li>
    <% else %>
      <li>
        <%= link_to "Home", root_path,class: 'fas fa-home nav-link text-light' %>
      </li>
      <li>
        <%= link_to "About", home_about_path,class: 'fas fa-link nav-link text-light' %>
      </li>
      <li>
        <%= link_to "Sign up", new_user_registration_path,class: 'fas fa-user-plus nav-link text-light' %>
      </li>
      <li>
        <%= link_to "Login", new_user_session_path, class: 'fas fa-sign-in-alt nav-link text-light' %>
      </li>
       <% end %>
        </ul>
      </div>
     </nav>
    </header>
    <%= yield %>
      <footer class="text-secondary pt-5 pb-4">
      <div class="container">
        <div class="row no-gutters">
          <div class="col-md-4">
            <a>
              <%= link_to "Home", root_path,class: 'fas fa-home' %>
            </a>
             <a>
              <%= link_to "About", home_about_path,class: 'fas fa-audio-description' %>
            </a>
             <a>
              <a href="mailto:hiroki.kojima0417@gmail.com" class="fas fa-envelope-square">Contact</a>
            </a>
          </div>
        </div>
      <div class="text-center">
        <a class="text-body mt-2 mb-3">@2021 ShoesProud</a>
      </div>
    </footer>
  </body>
</html>